SDK examples
partnero/partnero-php pull request #1
Opened 2023-05-26 10:05 UTC by OvidijusSobut

2023-05-26 11:38 UTC, mindaugasmailer commented on README.md
> +$partnero->partners()->list(limit: 10);
Maybe let remove variable names.

2023-05-26 11:39 UTC, mindaugasmailer commented on README.md
> +  ->setSurname("Surname")
Let remove surname too, we will move to use only name in the future

2023-05-26 11:45 UTC, mindaugasmailer commented on README.md
> +  ->setEmail('john.doe@mail.com')
Maybe we need to be consistent with double or single quotes. I'm voting for single.

2023-05-26 11:47 UTC, mindaugasmailer commented on README.md
> +## Settings
Drop settings part to the end, we need to think if we need this one at all.

2023-05-26 11:59 UTC, mindaugasmailer requested changes
I think main thing to be consistent through all readme

2023-05-29 07:03 UTC, mindaugasmailer commented on README.md
> +  ->setSurname("Surname")
hmmm, maybe lets leave it for partners and don't show for customers only 🤔

2023-05-29 19:24 UTC, gdmns approved these changes

2023-05-30 05:42 UTC, merged